@port = 4000
@hostname = localhost
@apiV1 = api/v1
@host = {{hostname}}:{{port}}
@contentType = application/json
@users = users
@categories = categories
@messages = messages

@nunPage = nunPage
@pageSize = pageSize


###
POST http://{{hostname}}:{{port}}/{{apiV1}}/register
content-type: {{contentType}}

{
  "userName": "Luciano",
  "email": "lucho@lucho",
  "password": "1234"
}

###
POST http://{{hostname}}:{{port}}/{{apiV1}}/login

###################### USERS ####################
# POST http://{{hostname}}:{{port}}/{{apiV1}}/{{users}}



### 
GET http://{{hostname}}:{{port}}/{{apiV1}}/{{users}}?{{nunPage}}=1&{{pageSize}}=2


###
GET http://{{hostname}}:{{port}}/{{apiV1}}/{{users}}/21
# Authorization: Bearer 'kgfkgjdñfkg'

###
PUT http://{{hostname}}:{{port}}/{{apiV1}}/{{users}}/9
content-type: {{contentType}}

{
  "userName": "Iraira",
  "alias": "mi mamá"
}

###
DELETE http://{{hostname}}:{{port}}/{{apiV1}}/{{users}}/29

###################### CATEGORIES ####################

POST http://localhost:4000/api/v1/categories
content-type: application/json

{
  "categoryName": "trabajo"
}

###
GET http://localhost:4000/api/v1/categories?nunPage=2&pageSize=2

###
GET http://localhost:4000/api/v1/categories/9

###
PUT http://localhost:4000/api/v1/categories/10
content-type: application/json

{
  "categoryName": "amigos"
}

###
DELETE http://localhost:4000/api/v1/categories/9

######################   MESSAGES   ####################

POST http://{{hostname}}:{{port}}/{{apiV1}}/{{messages}}/sendMessage
content-type: application/json

{
  "payload": "esto es una prueba para la ruta"
}

###
POST http://localhost:4000/api/v1/messages
content-type: application/json

{
  "content": "",
}

###
GET http://localhost:4000/api/v1/messages
###

GET http://localhost:4000/api/v1/messages?nunPage=2&pageSize=4

###
GET http://localhost:4000/api/v1/messages/89

###
PUT http://localhost:4000/api/v1/messages/90
content-type: application/json

{
  "content": "Feliz noche"
}

###
DELETE http://localhost:4000/api/v1/messages/90

### CREAR RELACION ENTRE MENSAJES Y CATEGORIAS #####
POST http://localhost:4000/api/v1/messages/90/categories
content-type: application/json

{
  "categoriesIds" : [7,10]
}

### OBTENER EL MENSAJE O GRUPOS DE MENSAJES POR UNA CATEGORÍA ###
GET http://localhost:4000/api/v1/categories/10/messages

### OBTENER LA CATEGORÍA O GRUPO DE CATEGORÍAS POR UN MENSAJE ###
GET http://localhost:4000/api/v1/messages/90/categories


################## CREAR RELACION ENTRE USUARIOS Y MENSAJES ##########
POST http://localhost:4000/api/v1/users/14/messages
content-type: application/json

{
  "messagesIds" : [89,90,94]
}

### OBTENER EL MENSAJE O GRUPOS DE MENSAJES POR UN USUARIO ###
GET http://localhost:4000/api/v1/users/14/messages

# ### OBTENER LA CATEGORÍA O GRUPO DE CATEGORÍAS POR UN MENSAJE ###
# GET http://localhost:4000/api/v1/messages/90/categories
