
###################### USERS ####################
POST http://localhost:4000/api/v1/users
content-type: application/json

{
  "userName": "Mathías",
  "alias": "mathius"
}

### 
GET http://localhost:4000/api/v1/users


###
GET http://localhost:4000/api/v1/users/11

###
PUT http://localhost:4000/api/v1/users/9
content-type: application/json

{
  "userName": "Iraira",
  "alias": "mamá"
}

###
DELETE http://localhost:4000/api/v1/users/11

###################### CATEGORIES ####################

POST http://localhost:4000/api/v1/categories
content-type: application/json

{
  "categoryName": "amigos"
}

###
GET http://localhost:4000/api/v1/categories

###
GET http://localhost:4000/api/v1/categories/9

###
PUT http://localhost:4000/api/v1/categories/10
content-type: application/json

{
  "categoryName": "amigos"
}

###
DELETE http://localhost:4000/api/v1/categories/9

######################   MESSAGES   ####################

###
POST http://localhost:4000/api/v1/users
content-type: application/json

{
  "userName": "Iraida",
  "alias": "mamá"
}

###
GET http://localhost:4000/api/v1/messages
###
GET http://localhost:4000/api/v1/messages/2

###
PUT http://localhost:4000/api/v1/messages/10
content-type: application/json

{
  "categoryName": "amigos"
}

###
DELETE http://localhost:4000/api/v1/messages/9