
###################### USERS ####################
POST http://localhost:4000/api/v1/users
content-type: application/json

{
  "userName": "Rut",
  "alias": "bestie"
}

### 
GET http://localhost:4000/api/v1/users


###
GET http://localhost:4000/api/v1/users/11

###
PUT http://localhost:4000/api/v1/users/9
content-type: application/json

{
  "userName": "Iraira",
  "alias": "mi mamá"
}

###
DELETE http://localhost:4000/api/v1/users/12

###################### CATEGORIES ####################

POST http://localhost:4000/api/v1/categories
content-type: application/json

{
  "categoryName": "trabajo"
}

###
GET http://localhost:4000/api/v1/categories

###
GET http://localhost:4000/api/v1/categories/9

###
PUT http://localhost:4000/api/v1/categories/10
content-type: application/json

{
  "categoryName": "amigos"
}

###
DELETE http://localhost:4000/api/v1/categories/9

######################   MESSAGES   ####################

###
POST http://localhost:4000/api/v1/messages
content-type: application/json

{
  "content": "",
}

###
GET http://localhost:4000/api/v1/messages
###
GET http://localhost:4000/api/v1/messages/2

###
PUT http://localhost:4000/api/v1/messages/10
content-type: application/json

{
  "categoryName": "Religión"
}

###
DELETE http://localhost:4000/api/v1/messages/88

###
POST http://localhost:4000/api/v1/messages/93/categories
content-type: application/json

{
  "categoriesIds" : [12]
}

### OBTENER EL MENSAJE O GRUPOS DE MENSAJES POR UNA CATEGORÍA ###
GET http://localhost:4000/api/v1/categories/11/messages
